### ISSUE TITLE
Greying out of buttons with no data doesn't work for pick-up points in Avoid

### ISSUE THREAD

**Issue by jamaps** [Nate-Wessel/urban-freight#49]
e.g. see Penguin layer for Edmonton.

I think this is caused by all pickup points being included in the same topojson file. So if one is there, then it thinks all are there

**Comment by Nate-Wessel** [comment]
This will be tricky. It might be easiest to break the data up by source, and then just rely on the current setup. There'd be some refactoring to do, but nothing too major I don't think. 

Versus all the asynchronous state passing that would be needed to get the status of the parsed data back up to each of the buttons.

**Comment by jamaps** [comment]
cool. I'm keeping the pick-up locations separate for now

**Comment by Nate-Wessel** [comment]
Done!
